### ISSUE TITLE
Code doesn't connect to debugger

### ISSUE THREAD

**Issue by rarcher-cerdi** [marcelvanworkum/pycharm-python-debug-server-docker#1]
Hi Marcel, Thank you for such an excellent step-by-step guide.

I would like to leave some information here for people following this guide.

There is a bug introduced in PyCharm 2024.3 which results in a failure of the container to connect to the Debug Server in PyCharm.

The observed behaviour:
The container outputs "This message prints before we attach the debugger" and then just sits there doing nothing (it's actually suspended).
PyCharm outputs "This message prints before we attach the debugger" but never receives a connection.

The solution is [described on YouTrack](https://youtrack.jetbrains.com/issue/PY-77357/Python-Debug-Server-with-pydevd-pycharm-stopped-working-in-2024.3):

  disable python.debug.use.single.port in Help | Find Action | Registry

Hopefully this will be fixed in the next release of PyCharm, then this issue can be resolved!
If it's not fixed, it might be worth adding this step to the Readme.

**Comment by marcelvanworkum** [comment]
Thanks for the note @rarcher-cerdi, I've added an addendum to the readme.
